### ISSUE TITLE
Unable to access m.ail.fail extension after installation

### ISSUE THREAD

**Issue by lawndartuk** [ACK-J/MailFail#2]
I feel like I might be being foolish but I've installed it on Firefox on Mac 127.02, same version on Windows 10.  The machines are fully patched to end of June 2024.  Neither shows the 'button' on the extension the browser.  I don't seem to be able to access it at all.  I can see that MailFail by Hacks and Hops is installed.  I've allowed all the permissions that are available.

How do I access it?

**Comment by ACK-J** [comment]
Is it in your extension bar?
https://support.mozilla.org/en-US/kb/extensions-button
